### ISSUE TITLE
Exception in GameClock.getExtraClocks after Game Interruption procedure ended

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/GameController#124]
After the Execute of a Game Interruption was called and the 10 seconds on the secondary clock were counted down, the following exception is thrown:

Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
        at data.states.GameClock.getExtraClocks(Unknown Source)
        at controller.ui.ui.components.ClockComponent.updateExtraClocks(Unknown Source)
        at controller.ui.ui.components.ClockComponent.update(Unknown Source)
        at controller.ui.ui.AbstractUI.update(Unknown Source)
        at controller.EventHandler.update(Unknown Source)
        at controller.EventHandler.access$000(Unknown Source)
        at controller.EventHandler$1.run(Unknown Source)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by sheepsy90** [comment]
I checked this out but I  don't know exactly what is going on. I think it might be some concurrency issue between the UI thread and the main thread but my Java knowledge isn't good enough to figure out how to fix it. :(
