### ISSUE TITLE
Problem in running Game Controller

### ISSUE THREAD

**Issue by black-sec** [RoboCup-Humanoid-TC/GameController#84]
hello, I have a question about GC 2018.1. I Build the Game controller without any problem. Anyway, when I want to run the GC in both Windows and Linux I hit the following error: Could you tell me what's wrong? Does it have a bug or I missed something?!
I wrote in terminal: java -jar GameController.jar -w
Error message : 
 Exception in thread "main" java.lang.NoClassDefFoundError: teamcomm/Config
	at data.teams.TeamsLoader.<clinit>(Unknown Source)
	at data.states.GamePreparationData.refreshTeams(Unknown Source)
	at data.states.GamePreparationData.<init>(Unknown Source)
	at controller.ui.setup.StartInput.<init>(Unknown Source)
	at controller.GameController.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: teamcomm.Config
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 5 more

**Comment by ftsell** [comment]
I have the same issue under linux using version 2018.1 and building from source according to the documentation.

**Comment by MaikePaetzel** [comment]
Is this still an open issue? And if it is, could you confirm that you ran the command from within the `build\jar` folder? This looks like the GameController saying it can't load the config data, which is usually the case if it is not executed from within the build folder.

**Comment by ftsell** [comment]
It's been some time since I commented on this issue so I don't really know any more
